### ISSUE TITLE
是否支持DCNv2？

### ISSUE THREAD

**Issue by cyymt** [shouxieai/tensorRT_cpp#13]

**Comment by Guanbin-Huang** [comment]
支持的，我们已经实现了CenterNet Res18 + DCN，提供了DCNv2的插件

**Comment by Guanbin-Huang** [comment]
> _No description provided._
src/tensorRT/onnxplugin/plugins/DCNv2.cu 
插件的cuda实现在这里，今晚之前，我们会推出 CenterNet 的从pytorch 到tensorRT的使用方法，敬请关注！！

**Comment by Guanbin-Huang** [comment]
CenterNet with DCNv2 tutorial has been released. You can refer to it in tutorial/2.0from_torch_to_trt for details
初级教程已经写完了，你可以查看tutorial/2.0from_torch_to_trt  @cyymt
