### ISSUE TITLE
 Error Code 1: Cuda Driver (invalid argument)

### ISSUE THREAD

**Issue by l1uw3n** [shouxieai/tensorRT_cpp#17]
![image](https://user-images.githubusercontent.com/24247258/134800443-04771f28-6c0c-40aa-bbda-bc4a0361a941.png)
显卡没有被占用转模型时候为什么无法申请内存？如何排查错误？
cuda版本10.2其它的都是下载的提供的额包里的库。

**Comment by shouxieai** [comment]
查看你的显卡型号应该配的驱动版本，更新驱动。然后查看cuda与驱动的适配是否合适。更新cuda。达到全部适配为止

**Comment by l1uw3n** [comment]
谢谢，我恰好找到一个匹配表，我试试
![image](https://user-images.githubusercontent.com/24247258/134800891-13d89f56-6be9-47ce-b3f2-af15be276f99.png)
