### ISSUE TITLE
我的笔记本算力是5.0，改了之后重新生成失败，但是按照UP的6.1就没这个问题，是不是我哪里没配置好

### ISSUE THREAD

**Issue by wjyangqun** [shouxieai/tensorRT_cpp#18]
![2](https://user-images.githubusercontent.com/62162800/134803564-78375cec-d267-486a-88e9-df8030fac129.png)
![ME9N@@N9ZSLFLZ(HJCDXQO1](https://user-images.githubusercontent.com/62162800/134803568-5289613b-3859-4dec-a6e0-e234ad642cec.png)

**Comment by shouxieai** [comment]
5.0失败一般是因为不支持fp16
你得去掉fp16部分的代码，这个我暂时没有做的太友好
只使用fp32/int8是没问题的
6.1的时候你能编译成功，可能不见得能执行成功

**Comment by wjyangqun** [comment]
谢谢大佬，6.1的时候确实报算力的错
