### ISSUE TITLE
希望大佬，我在linux下编译出现如下错误

### ISSUE THREAD

**Issue by yang-gis** [shouxieai/tensorRT_cpp#23]
希望大佬，我在linux下编译出现如下错误：
in function `CUDATools::check_driver(cudaError_enum, char const*, int, char const*)':
/home/yjy/test_trt_new/common/cuda_tools.cpp:15: undefined reference to `cuGetErrorString'
/usr/bin/ld: /home/yjy/test_trt_new/common/cuda_tools.cpp:16: undefined reference to `cuGetErrorName'

请问是怎么回事啊

**Comment by yang-gis** [comment]
已解决

**Comment by Darren759** [comment]
> 已解决

请问怎么解决的
