### ISSUE TITLE
error: #error This file was generated by an older version of protoc which is

### ISSUE THREAD

**Issue by ousinkou** [shouxieai/tensorRT_cpp#3]
编译代码时出现这个问题，问题文件来自于src/tensorRT/onnx文件夹里的几个文件的预处理部分。readme上说这几个文件是ONNX编译提取的结果。我尝试编译ONNX找到这几个文件复制替换，但是仍然有问题。
请问有没有办法规避这个问题呢？或者是我编译的ONNX版本不对？

**Comment by shouxieai** [comment]
建议配置protobuf3.11.4，不知道你是否配置这个版本

**Comment by shouxieai** [comment]
你可能配置了更新的protobuf，我是基于3.11.4编译得到的pb文件。也因此才会提示pb是旧版本产生的。

**Comment by ousinkou** [comment]
是的，我换成3.11.4的protobuf版本，问题已经解决。
代码链接protobuf时有点问题，将CMakefile.txt中protobuf对应代码替换成

```
find_package(Protobuf)
target_link_libraries(pro ${PROTOBUF_LIBRARY})
```

这种形式。现在编译运行成功了。
