### ISSUE TITLE
win10配置的小问题

### ISSUE THREAD

**Issue by JustinNober** [shouxieai/tensorRT_cpp#7]
win10步骤中的：（修改 Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 10.0.props" / 为你配置的CUDA路径）能不能给一个具体例子。 谢谢了 比如我这样对不对？$(VCTargetsPath)\C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\extras\visual_studio_integration\MSBuildExtensions\CUDA 10.2.props" /

**Comment by shouxieai** [comment]
你的例子中，应该是：`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\extras\visual_studio_integration\MSBuildExtensions\CUDA 10.2.props`
如果你配置了cuda，你可以新建一个可以编译cuda的工程，然后打开查看他写的啥

**Comment by JustinNober** [comment]
我下午调好了，但是我vs2019 一直报   MSB8041：此项目需要 MFC 库
